name: redpoint-haskell
version: 0.0.0.0
github: "eatobin/redpoint-haskell"
license: BSD-3-Clause
author: "Eric Tobin"
maintainer: "eatobin@gmail.com"
copyright: "None"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            None

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/eatobin/redpoint-haskell#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - hspec
  - monad-loops
  - mtl
  - random
  - raw-strings-qq
  - stm
  - vector

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  redpoint-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - redpoint-haskell
    when:
      - condition: false
        other-modules: Paths_redpoint_haskell

tests:
  redpoint-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - redpoint-haskell
